# Generated by Django 3.1.1 on 2020-09-07 17:35

from django.db import migrations, models
import pages.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('header_img', models.ImageField(upload_to=pages.models.event_uploads)),
                ('event_url', models.URLField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
