# Generated by Django 3.1.1 on 2020-09-19 16:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200907_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='OralHistoriesPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Cold War Oral Histories Page',
                'verbose_name_plural': 'Cold War Oral Histories Page',
            },
        ),
    ]
