# Generated by Django 3.1.1 on 2020-09-19 17:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_oralhistoriespage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFlightSimulatorPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blueprint', tinymce.models.HTMLField(verbose_name='Blueprint Digitization Project')),
                ('centrifuge', tinymce.models.HTMLField(verbose_name='Centrifuge Logbook Digitization')),
                ('tours', tinymce.models.HTMLField(verbose_name='Tours of The Fuge')),
            ],
            options={
                'verbose_name': 'Dynamic Flight Simulator Page',
                'verbose_name_plural': 'Dynamic Flight Simulator Page',
            },
        ),
    ]
