# Generated by Django 3.1.1 on 2020-09-19 19:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_nadcphoto_nadcphotocomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NADCPhotoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField(verbose_name='Page Text')),
            ],
            options={
                'verbose_name': 'NADC Photo Page',
                'verbose_name_plural': 'NADC Photo Page',
            },
        ),
    ]
