# Generated by Django 3.1.1 on 2020-09-23 12:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_nadcphotopage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nadcphoto',
            options={'ordering': ['-created_at'], 'verbose_name': 'NADC Photo', 'verbose_name_plural': 'NADC Photos'},
        ),
        migrations.AlterModelOptions(
            name='nadcphotocomment',
            options={'ordering': ['-date'], 'verbose_name': 'NADC Photo Comment', 'verbose_name_plural': 'NADC Photo Comments'},
        ),
        migrations.AddField(
            model_name='dynamicflightsimulatorpage',
            name='intro',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Page Introduction'),
        ),
        migrations.AlterField(
            model_name='dynamicflightsimulatorpage',
            name='blueprint',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Blueprint Digitization Project'),
        ),
        migrations.AlterField(
            model_name='dynamicflightsimulatorpage',
            name='centrifuge',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Centrifuge Logbook Digitization'),
        ),
        migrations.AlterField(
            model_name='dynamicflightsimulatorpage',
            name='tours',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Tours of The Fuge'),
        ),
    ]
