# Generated by Django 3.1.1 on 2020-09-24 00:06

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200923_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('HIOB', 'History In Our Backyard'), ('MOVIE', 'Movie Night'), ('AVT', 'Annual Veterans Tribute'), ('OTHER', 'Other Activites')], default='HIOB', max_length=5),
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=pages.models.event_uploads)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.event')),
            ],
        ),
    ]
