# Generated by Django 3.1.1 on 2020-09-24 00:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200923_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiob', tinymce.models.HTMLField(verbose_name='History In Our Backyard')),
                ('movie', tinymce.models.HTMLField(verbose_name='Movie Nights')),
                ('avt', tinymce.models.HTMLField(verbose_name='Annual Veterans Tribute')),
                ('other', tinymce.models.HTMLField(verbose_name='Other Activities')),
            ],
            options={
                'verbose_name': 'Event Category Descriptions',
                'verbose_name_plural': 'Event Category Descriptions',
            },
        ),
    ]
