# Generated by Django 3.1.1 on 2020-10-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_nadcphotocomment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicflightsimulatorpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='eventdescriptions',
            name='other',
        ),
    ]
