# Generated by Django 3.1.1 on 2021-08-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210310_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='nadcphoto',
            name='tags',
            field=models.ManyToManyField(to='pages.PhotoTag'),
        ),
    ]
