# Generated by Django 3.1.1 on 2021-08-18 01:54

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210805_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='WGNASPhotoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.nadcphoto')),
            ],
            options={
                'verbose_name': 'WGNAS Photo Comment',
                'verbose_name_plural': 'WGNAS Photo Comments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WGNASPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=pages.models.wgnas_uploads)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='pages.PhotoTag')),
            ],
            options={
                'verbose_name': 'WGNAS Photo',
                'verbose_name_plural': 'WGNAS Photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NAPCPhotoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.nadcphoto')),
            ],
            options={
                'verbose_name': 'NAPC Photo Comment',
                'verbose_name_plural': 'NAPC Photo Comments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NAPCPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=pages.models.napc_uploads)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='pages.PhotoTag')),
            ],
            options={
                'verbose_name': 'NAPC Photo',
                'verbose_name_plural': 'NAPC Photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
