# Generated by Django 3.1.1 on 2021-08-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20210823_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadcphoto',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pages.PhotoTag'),
        ),
        migrations.AlterField(
            model_name='napcphoto',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pages.PhotoTag'),
        ),
        migrations.AlterField(
            model_name='wgnasphoto',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pages.PhotoTag'),
        ),
    ]
