# Generated by Django 3.1.1 on 2022-01-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20210823_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phototag',
            options={'ordering': ['tag']},
        ),
        migrations.AlterField(
            model_name='napcphotocomment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.napcphoto'),
        ),
    ]
