# Generated by Django 3.1.1 on 2021-02-01 16:34

import catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'File Type',
                'verbose_name_plural': 'File Types',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Accession Number')),
                ('accession_date', models.DateField(auto_now_add=True, null=True, verbose_name='Accession Date')),
                ('obj_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Object Date')),
                ('obj_file', models.FileField(blank=True, null=True, upload_to=catalog.models.catalog_files, verbose_name='Object')),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('approx_obj_date', models.DateField(blank=True, null=True, verbose_name='Approximate Object Date')),
                ('start_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Start Year Range')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='End Year Range')),
                ('provenance', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('accession_img', models.ImageField(blank=True, null=True, upload_to=catalog.models.catalog_files, verbose_name='Accession Image')),
                ('accession_img_caption', models.TextField(blank=True, null=True, verbose_name='Accession Image Caption')),
                ('accession_img_description', models.TextField(blank=True, null=True, verbose_name='Accession Image Description')),
                ('downloadable', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('category', models.ManyToManyField(related_name='categories', to='catalog.Category')),
                ('collection', models.ManyToManyField(related_name='collections', to='catalog.Collection')),
                ('file_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.filetype', verbose_name='File Type')),
                ('keyword', models.ManyToManyField(blank=True, null=True, related_name='keywords', to='catalog.Keyword')),
            ],
            options={
                'verbose_name': 'Catalog Item',
                'verbose_name_plural': 'Catalog Items',
            },
        ),
    ]
