# Generated by Django 3.1.1 on 2021-02-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='accession_date',
            field=models.DateField(blank=True, null=True, verbose_name='Accession Date'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='obj_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Object Name'),
        ),
    ]
