# Generated by Django 3.1.1 on 2021-02-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210201_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogitem',
            old_name='source',
            new_name='source_name',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='keyword',
            field=models.ManyToManyField(related_name='keywords', to='catalog.Keyword'),
        ),
    ]
